spring:
  application:
    name: consumer

  cloud:
    function:
      definition: processRiderLocation;processRiderStatus
    stream:
      function:
        definition: processRiderLocation;processRiderStatus
      bindings:
        processRiderLocation-in-0:
          destination: topic-1
        processRiderStatus-in-0:
          destination: topic-2
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8081
